Responsiveness Header
GETLN/mintgate pull request #18
Opened 2023-01-20 17:20 UTC by IgboPharaoh

-Modified button props and types to accept responsive styles. 
-Made connect lightning button to be responsive across screens.  
-Made header responsive. 
-Add menu icon for mobile screens

2023-01-20 19:32 UTC, okjodom commented on src/components/Button.tsx
>  			{button.label}
suggestion: follow up: let's make this generic using child props instead of a string label

2023-01-20 19:33 UTC, okjodom commented on src/components/Button.tsx
>  export const Button = (button: ButtonProps) => {
let's name the parameter as props

2023-01-20 19:33 UTC, okjodom commented on src/components/Button.tsx
>  export const Button = (button: ButtonProps) => {
`(props: ButtonProps)` instead of `(button: ButtonProps)`

2023-01-20 19:35 UTC, okjodom commented on src/components/Button.tsx
> +	const {
we can destructure a most of these props directly in to the rendered element, and not have to declare them here.

`<CustomButton someDefaultProp={} {...props} />`

2023-01-21 23:44 UTC, okjodom requested changes

2023-01-22 05:03 UTC, IgboPharaoh commented on src/components/ConnectLightning.tsx
>  		/>
So, I Intentionally left that so as not to break the federation card and I'm fixing them individually in different commits. But I guess I'll make the label to be a conditional prop, remove them where need be, and update all buttons affected in this commit

2023-01-22 05:11 UTC, okjodom commented on src/components/ConnectLightning.tsx
>  		/>
@IgboPharaoh , another way of fixing this, (temporarily) is to do `{props.label || props.children}` within Button. Would help avoid changing too many things at once

2023-01-22 05:20 UTC, IgboPharaoh commented on src/components/ConnectLightning.tsx
>  		/>
but just as you highlighted that's like a temporary fix, you suggested earlier we make it generic using the child prop, and I believe that'll be better

2023-01-22 05:22 UTC, okjodom commented on src/components/ConnectLightning.tsx
>  		/>
it's temporary because you can follow up with a PR to completely remove the label prop. That is a wider reaching change

2023-01-22 05:45 UTC, okjodom approved these changes
Thanks for the continued polish! looking good

2023-01-22 05:45 UTC, merged